apiVersion: v1
data:
  V1__Create_users_table.sql: |
    CREATE TABLE users(
      id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
      name VARCHAR(100) NOT NULL,
      email VARCHAR(255) NOT NULL UNIQUE,
      password VARCHAR(255) NOT NULL,
      birthday DATE
    );
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: migration-config
  namespace: chat-app
