apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-front-deployment
  namespace: chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-front
  template:
    metadata:
      labels:
        app: chat-front
    spec:
      containers:
        - name: chat-front
          image: fperezb/lab-chat-frontend:main
          ports:
            - containerPort: 80
              name: http-chat-svc
      restartPolicy: Always
