apiVersion: v1
kind: Service
metadata:
  name: chat-front-service
  namespace: chat-app
  labels:
    app: chat-front
spec:
  type: LoadBalancer
  selector:
    app: chat-front
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      nodePort: 32000
