apiVersion: v1
kind: Service
metadata:
  name: chat-front-service
  namespace: chat-app
  labels:
    app: chat-front
spec:
  type: NodePort
  selector:
    app: chat-front
  ports:
    - protocol: TCP
      name: chat-front
      port: 80
      targetPort: http-chat-svc
      nodePort: 30080
