apiVersion: v1
kind: Service
metadata:
  name: users-svc-service
  namespace: chat-app
  labels:
    app: users-svc
spec:
  type: NodePort
  selector:
    app: users-svc
  ports:
    - protocol: TCP
      name: users-api
      port: 3000
      targetPort: http-users-api
      nodePort: 32000
