apiVersion: v1
kind: Service
metadata:
  name: users-svc-service
  namespace: chat-app
  labels:
    app: users-svc
spec:
  type: LoadBalancer
  selector:
    app: users-svc
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 31000
