apiVersion: v1
kind: Service
metadata:
  name: ws-service-service
  namespace: chat-app
  labels:
    app: ws-service
spec:
  type: LoadBalancer
  selector:
    app: ws-service
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      nodePort: 31001
