apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-service-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-service
  template:
    metadata:
      labels:
        app: ws-service
    spec:
      containers:
        - name: ws-service
          image: USUARIO/labcna-ws-server:version
          args:
            - "node"
            - "index.js"
          env:
            - name: PORT
              value: "3001"
          ports:
            - containerPort: 3001
              name: ws-svc
      restartPolicy: Always
