apiVersion: v1
kind: Service
metadata:
  name: ws-server-service
  namespace: chat-app
  labels:
    app: ws-service
spec:
  type: NodePort
  selector:
    app: ws-service
  ports:
    - protocol: TCP
      name: ws-svc
      port: 3001
      targetPort: ws-svc
      nodePort: 32001
